spring.application.name=as2-spring-boot-logging-and-security

spring.h2.console.enabled=true
spring.h2.console.path=/h2

spring.datasource.url=jdbc:h2:mem:uniDB
spring.datasource.username=root
spring.datasource.password=pass

spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=10

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Set logging levels for specific packages or classes
logging.level.org.springframework.web=DEBUG
logging.level.isgandarli.zumrud.as2springbootloggingandsecurity.controller.BusinessController=INFO
logging.level.isgandarli.zumrud.as2springbootloggingandsecurity.controller.RegistrationController=INFO
logging.level.isgandarli.zumrud.as2springbootloggingandsecurity.controller.CourseController=INFO
logging.level.isgandarli.zumrud.as2springbootloggingandsecurity.security=info

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=zz.isgandarli@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
